# Basic metadata configuration for your blog.
baseURL = 'https://urieles.co/'
languageCode = 'en-us'
title = "Alex's blog"
author = "aeurielesn"
theme = 'bear'

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"
